{ config, lib, ... }:
let
  applications = [
    "age"
    "bat"
    "bkt"
    "btop"
    "coding-agents"
    "curl"
    "delta"
    "devenv"
    "direnv"
    "eza"
    "fd"
    "forgejo-cli"
    "fzf"
    "gh"
    "ghostty"
    "git"
    "git-branches"
    "git-delete-branches"
    "gnutar"
    "helium"
    "jq"
    "lsof"
    "mongodb-compass"
    "mpv"
    "neovim"
    "nushell"
    "openssh"
    "project-run"
    "ripgrep"
    "starship"
    "t3code"
    "tailscale"
    "tealdeer"
    "unzip"
    "webapps"
    "wget"
    "xz"
    "yazi"
    "yq-go"
    "zip"
    "zoxide"
    "zen"
  ];
in
{
  flake.modules = lib.genAttrs [ "nixos" "darwin" ] (platform: {
    common-applications.imports = map (name: config.flake.modules.${platform}.${name}) applications;
  });
}
