#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title __APP_NAME__
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='__APP_URL__' \
  "$@"
