#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title AniList Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://anilist.co' \
  "$@"
