#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title Gmail Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://mail.google.com' \
  "$@"
