#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title Habitica Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://habitica.com/' \
  "$@"
