#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title Proton Drive Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://drive.proton.me/u/0/' \
  "$@"
