#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title Proxmox Virtual Environment (TailScale) Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://pve.ts.rafr.dev' \
  "$@"
