#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title Sharepoint (absences) Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://groupsolver.sharepoint.com/default.aspx' \
  "$@"
