#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title T3 Chat Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://t3.chat' \
  "$@"
