#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title Tesco (potraviny) Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://potravinydomov.itesco.sk/shop/sk-SK/landing/groceries' \
  "$@"
