#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title Tipos Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://tipos.sk' \
  "$@"
