#!/bin/zsh
# @raycast.schemaVersion 1
# @raycast.title Wotaku Web App
# @raycast.mode silent
# @raycast.packageName Web Apps

exec /Applications/Chromium.app/Contents/MacOS/Chromium \
  --app='https://wotaku.wiki' \
  "$@"
